import {useState} from 'react';
import {View,ScrollView,Text,TextInput,Pressable,StyleSheet} from 'react-native';
import {accountLogin,accountStatus,accountLogout,openAccountPortal} from './platform/commercialAccount';
export function CommercialPanel({close}:{close:()=>void}){
 const[email,setEmail]=useState(''),[password,setPassword]=useState(''),[account,setAccount]=useState<any>(null),[message,setMessage]=useState('');
 async function run(fn:()=>Promise<any>){try{const r=await fn();if(r?.user)setAccount(r);setMessage('Operação concluída');}catch(e){setMessage(e instanceof Error?e.message:'Conta indisponível');}}
 const button=(title:string,fn:()=>void)=><Pressable style={styles.button} onPress={fn}><Text style={styles.buttonText}>{title}</Text></Pressable>;
 return <ScrollView keyboardShouldPersistTaps="handled" keyboardDismissMode="on-drag" contentContainerStyle={styles.panel}><Text style={styles.title}>Conta RB</Text><Text style={styles.text}>A conta comercial e o pareamento com o PC utilizam credenciais separadas.</Text>{account?<><Text style={styles.text}>{account.user.email} — {account.plan}</Text><Text style={styles.text}>Assinatura: {account.subscription.status}</Text>{account.plan==='FREE'?<Text style={styles.text}>Recursos PRO indisponíveis. Os dados salvos permanecem preservados.</Text>:null}</>:<><TextInput accessibilityLabel="E-mail da conta RB" style={styles.input} value={email} onChangeText={setEmail} keyboardType="email-address" autoCapitalize="none" placeholder="E-mail" placeholderTextColor="#bbb"/><TextInput accessibilityLabel="Senha da conta RB" style={styles.input} value={password} onChangeText={setPassword} secureTextEntry placeholder="Senha" placeholderTextColor="#bbb"/>{button('Entrar',()=>{void run(async()=>{try{return await accountLogin(email,password);}finally{setPassword('');}});})}</>}{button('Atualizar conta',()=>{void run(accountStatus);})}{button('Gerenciar assinatura / criar conta',()=>{void run(openAccountPortal);})}{button('Sair da conta RB',()=>{void run(async()=>{await accountLogout();setAccount(null);});})}<Text style={styles.text}>{message}</Text>{button('Voltar ao aplicativo',close)}</ScrollView>;
}
const styles=StyleSheet.create({panel:{padding:24,backgroundColor:'#15181b',flexGrow:1},title:{fontSize:28,color:'white',fontWeight:'700'},text:{color:'#ddd',marginVertical:8},input:{backgroundColor:'#24282c',color:'white',padding:12,marginVertical:6},button:{backgroundColor:'#b7ff3c',padding:12,marginVertical:5},buttonText:{color:'#101510',fontWeight:'700'}});
