const {test}=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {verifyLicense,EntitlementService,FREE}=require('../app/services/license-service.cjs');
const security=require('../app/services/profile-security.js');
const {FinancialStorage}=require('../app/services/financial-storage.cjs');
test('assinatura, instalação, tolerância offline, relógio e adulteração',()=>{
 const k=crypto.generateKeyPairSync('ed25519'),key=k.publicKey.export({type:'spki',format:'pem'}),now=Date.now();
 const p={version:1,issuer:'rb-commercial',audience:'rb-gestao',installationId:'pc',plan:'PRO',status:'active',issuedAt:new Date(now).toISOString(),validUntil:new Date(now+86400000).toISOString(),offlineGraceUntil:new Date(now+7*86400000).toISOString(),entitlements:{features:{investments:true},limits:{profiles:10,devices:5}}};
 const payload=Buffer.from(JSON.stringify(p)).toString('base64url'),signed={payload,signature:crypto.sign(null,Buffer.from(payload),k.privateKey).toString('base64url')};
 assert.equal(verifyLicense(signed,key,'pc',now).plan,'PRO');assert.equal(verifyLicense(signed,key,'pc',now+2*86400000).offline,true);
 assert.equal(verifyLicense(signed,key,'pc',now+8*86400000),null);assert.equal(verifyLicense(signed,key,'other',now),null);assert.equal(verifyLicense({...signed,payload:payload+'a'},key,'pc',now),null);assert.equal(verifyLicense(signed,key,'pc',now,now+3600000),null);
 assert.equal(new EntitlementService(()=>FREE).can('investments'),false);
});
test('PIN PBKDF2 e compatibilidade SHA-256 sem aceitar senha errada',async()=>{const p=await security.create('123456');assert.equal(p.passwordVersion,2);assert.equal(await security.verify('123456',p),true);assert.equal(await security.verify('654321',p),false);assert.notEqual((await security.create('123456')).passwordSalt,p.passwordSalt);const old={id:'p',passwordHash:crypto.createHash('sha256').update('p|RB-GESTAO|1234').digest('hex')};assert.equal(await security.verify('1234',old),true);});
test('downgrade preserva dados e impede nova alteração premium',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'rb-test-'));try{let premium=true;const store=new FinancialStorage(dir,new EntitlementService(()=>premium?{entitlements:{features:{investments:true},limits:{profiles:10}}}:FREE));const base={profiles:[{id:'1'}],sharedData:{investments:[{id:'i',value:20}]}};store.save(base,{migration:true});premium=false;assert.deepEqual(store.load(),base);assert.throws(()=>store.save({...base,sharedData:{investments:[]}}));assert.deepEqual(store.load(),base);}finally{fs.rmSync(dir,{recursive:true,force:true});}});
test('armazenamento inválido nunca sobrescreve o original',()=>{const Storage=require('../app/services/storage-service.js'),map=new Map([['rb_gestao_financeira_profiles_v1','{corrupt']]),adapter={getItem:k=>map.get(k),setItem:(k,v)=>map.set(k,v)},s=new Storage(adapter);assert.throws(()=>s.load());assert.throws(()=>s.save({profiles:[]}));assert.equal(map.get('rb_gestao_financeira_profiles_v1'),'{corrupt');});
test('Electron mantém isolamento e cofre não aceita premium por ambiente',()=>{const main=fs.readFileSync(path.join(__dirname,'../electron-main.cjs'),'utf8');for(const text of ['contextIsolation: true','nodeIntegration: false','sandbox: true','devTools: false','requireDesktopSender'])assert.ok(main.includes(text));const license=fs.readFileSync(path.join(__dirname,'../app/services/license-service.cjs'),'utf8');assert.ok(!license.includes('process.env'));});
