name = "rb-gestao-subscriptions"
main = "src/index.js"
compatibility_date = "2026-10-07"

[[d1_databases]]
binding = "DB"
database_name = "rb-gestao-subscriptions"
database_id = "de119220-9c6a-419f-88bb-e6fd0128d096"

[[kv_namespaces]]
binding = "KV"
id = "d4615088952543bfab90767cefaed8f9"

[vars]
APP_AUDIENCE = "rb-gestao"
ISSUER = "rb-commercial"

[observability]
enabled = true

[observability.traces]
enabled = true
