const json=(body,status=200,headers={})=>new Response(JSON.stringify(body),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store',...headers}});
const id=()=>crypto.randomUUID();
const b64=v=>btoa(String.fromCharCode(...new Uint8Array(v))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');
const text=async r=>{try{return await r.json()}catch{return {}}};
async function hash(value){const data=new TextEncoder().encode(value);const digest=await crypto.subtle.digest('SHA-256',data);return b64(digest);}
async function password(value,salt){const material=await crypto.subtle.importKey('raw',new TextEncoder().encode(value),'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',salt:new TextEncoder().encode(salt),iterations:120000,hash:'SHA-256'},material,256);return b64(bits);}
function bearer(request){return String(request.headers.get('authorization')||'').replace(/^Bearer\s+/i,'');}
async function body(request){return text(request);}
async function userFrom(request,env){const token=bearer(request);if(!token)return null;const row=await env.DB.prepare('SELECT u.* FROM users u JOIN refresh_tokens t ON t.user_id=u.id WHERE t.hash=? AND t.revoked_at IS NULL AND t.expires_at>?').bind(await hash(token),new Date().toISOString()).first();return row||null;}
async function signLicense(payload,env){const pem=env.LICENSE_PRIVATE_KEY.replace(/\\n/g,'\n');const binary=Uint8Array.from(atob(pem.replace(/-----[^-]+-----/g,'').replace(/\s/g,'')),c=>c.charCodeAt(0));const key=await crypto.subtle.importKey('pkcs8',binary,{name:'RSASSA-PKCS1-v1_5',hash:'SHA-256'},false,['sign']);const encoded=b64(new TextEncoder().encode(JSON.stringify(payload)));const sig=await crypto.subtle.sign('RSASSA-PKCS1-v1_5',key,new TextEncoder().encode(encoded));return {payload:encoded,signature:b64(sig)};}
async function issueLicense(user,body,env){const installationId=String(body.installationId||'');if(!installationId)throw Error('installationId obrigatório');const now=new Date(),valid=new Date(now.getTime()+30*86400000),grace=new Date(valid.getTime()+7*86400000);const existing=await env.DB.prepare('SELECT id FROM installations WHERE id=?').bind(installationId).first();if(existing&&existing.user_id&&existing.user_id!==user.id)throw Error('Instalação vinculada a outra conta');await env.DB.prepare('INSERT INTO installations(id,user_id,name,platform,app_version,last_seen,revoked_at) VALUES(?,?,?,?,?,?,NULL) ON CONFLICT(id) DO UPDATE SET user_id=excluded.user_id,name=excluded.name,platform=excluded.platform,app_version=excluded.app_version,last_seen=excluded.last_seen,revoked_at=NULL').bind(installationId,user.id,String(body.name||'RB Gestão'),String(body.platform||'windows'),String(body.appVersion||''),now.toISOString()).run();const payload={version:1,issuer:env.ISSUER||'rb-commercial',audience:env.APP_AUDIENCE||'rb-gestao',installationId,plan:'PRO',status:'active',issuedAt:now.toISOString(),validUntil:valid.toISOString(),offlineGraceUntil:grace.toISOString(),entitlements:{features:{mobileAccess:true,automaticBackup:true},limits:{profiles:20,devices:10}}};const license=await signLicense(payload,env);await env.DB.prepare('INSERT INTO licenses(id,installation_id,plan,status,issued_at,valid_until,offline_grace_until,payload,signature) VALUES(?,?,?,?,?,?,?,?,?)').bind(id(),installationId,'PRO','active',payload.issuedAt,payload.validUntil,payload.offlineGraceUntil,license.payload,license.signature).run();return license;}
export default {async fetch(request,env){const url=new URL(request.url);if(request.method==='OPTIONS')return new Response(null,{headers:{'access-control-allow-origin':'*','access-control-allow-headers':'authorization,content-type','access-control-allow-methods':'GET,POST,OPTIONS'}});try{if(url.pathname==='/health')return json({ok:true,service:'rb-gestao-subscriptions'});if(url.pathname==='/v1/auth/login'&&request.method==='POST'){const b=await body(request),u=await env.DB.prepare('SELECT * FROM users WHERE email=?').bind(String(b.email||'').toLowerCase()).first();if(!u||u.password_hash!==await password(String(b.password||''),u.id))return json({error:'Credenciais inválidas'},401);const token=crypto.randomUUID()+crypto.randomUUID(),expires=new Date(Date.now()+30*86400000).toISOString();await env.DB.prepare('INSERT INTO refresh_tokens(hash,user_id,expires_at) VALUES(?,?,?)').bind(await hash(token),u.id,expires).run();return json({accessToken:token,refreshToken:token});}if(url.pathname==='/v1/account'&&request.method==='GET'){const u=await userFrom(request,env);if(!u)return json({error:'Não autorizado'},401);const sub=await env.DB.prepare('SELECT * FROM subscriptions WHERE user_id=? ORDER BY current_period_end DESC LIMIT 1').bind(u.id).first();return json({user:{id:u.id,name:u.name,email:u.email,verified:Boolean(u.verified)},subscription:sub||{plan:'PRO',status:'manual_vip'}});}if(url.pathname==='/v1/licenses/activate'&&request.method==='POST'){const u=await userFrom(request,env);if(!u)return json({error:'Não autorizado'},401);return json(await issueLicense(u,await body(request),env));}if(url.pathname==='/v1/devices'&&request.method==='GET'){const u=await userFrom(request,env);if(!u)return json({error:'Não autorizado'},401);const rows=await env.DB.prepare('SELECT * FROM installations WHERE user_id=? ORDER BY last_seen DESC').bind(u.id).all();return json(rows.results||[]);}if(url.pathname.startsWith('/v1/devices/')&&request.method==='DELETE'){const u=await userFrom(request,env);if(!u)return json({error:'Não autorizado'},401);await env.DB.prepare('UPDATE installations SET revoked_at=? WHERE id=? AND user_id=?').bind(new Date().toISOString(),decodeURIComponent(url.pathname.split('/').pop()),u.id).run();return json({ok:true});}return json({error:'Not found'},404);}catch(error){return json({error:error.message||'Erro interno'},500);}}};
