let access='';const $=id=>document.getElementById(id);const message=v=>{$('message').textContent=v||'';};const form=id=>Object.fromEntries(new FormData($(id)));
async function api(path,body,method='GET'){const r=await fetch(path,{method,headers:{'Content-Type':'application/json',...(access?{Authorization:'Bearer '+access}:{})},body:body===undefined?undefined:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw Error(data.error||'Falha na solicitação');return data;}
async function run(fn){try{await fn();}catch(e){message(e.message);}}
function metric(label,value,accent=''){return `<div class="metric ${accent}"><small>${label}</small><strong>${value}</strong></div>`;}
function renderCustomers(rows){const box=$('customers');if(!rows.length){box.innerHTML='<p class="muted">Nenhum cliente encontrado.</p>';return;}box.innerHTML='<table><thead><tr><th>Cliente</th><th>Plano</th><th>Status</th><th>Dispositivos</th><th>Ações</th></tr></thead><tbody>'+rows.map(r=>`<tr><td><strong>${esc(r.name)}</strong><small>${esc(r.email)}</small></td><td>${esc(r.subscription?.plan||'FREE')}</td><td><span class="badge ${r.status==='blocked'?'blocked':'active'}">${r.status==='blocked'?'Bloqueado':'Ativo'}</span></td><td>${r._count?.devices||0}</td><td><button class="small" data-edit="${r.id}">Editar</button><button class="small ${r.status==='blocked'?'primary':'danger'}" data-block="${r.id}">${r.status==='blocked'?'Desbloquear':'Bloquear'}</button></td></tr>`).join('')+'</tbody></table>';}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
async function load(){const [o,rows]=await Promise.all([api('/v1/admin/overview'),api('/v1/admin/customers?q='+encodeURIComponent($('search').value)+'&status='+encodeURIComponent($('status-filter').value))]);$('metrics').innerHTML=metric('Clientes',o.users)+metric('Ativos',o.active,'good')+metric('Bloqueados',o.blocked,'bad')+metric('Dispositivos',o.devices)+metric('Assinaturas PRO',o.paidSubscriptions,'good');renderCustomers(rows);}
function showForm(row){const f=$('customer-form');f.hidden=false;$('close-form').hidden=false;f.elements.id.value=row?.id||'';f.elements.name.value=row?.name||'';f.elements.email.value=row?.email||'';f.elements.email.disabled=!!row;f.elements.password.required=!row;f.elements.password.value='';f.elements.plan.value=row?.subscription?.plan||'FREE';f.elements.status.value=row?.status||'active';f.closest('.panel').scrollIntoView({behavior:'smooth'});}
$('login-form').onsubmit=e=>{e.preventDefault();void run(async()=>{const r=await api('/v1/admin/login',form('login-form'),'POST');access=r.accessToken;$('login').hidden=true;$('dashboard').hidden=false;$('logout').hidden=false;await load();message('Painel conectado.');});};
$('customer-form').onsubmit=e=>{e.preventDefault();void run(async()=>{const b=form('customer-form'),id=b.id;delete b.id;if(!b.password)delete b.password;if(id)await api('/v1/admin/customers/'+encodeURIComponent(id),b,'PATCH');else await api('/v1/admin/customers',b,'POST');$('customer-form').hidden=true;$('close-form').hidden=true;await load();message('Cliente salvo.');});};
$('new-customer').onclick=()=>showForm();$('close-form').onclick=()=>{$('customer-form').hidden=true;$('close-form').hidden=true;};$('reload').onclick=()=>void run(load);$('search').oninput=()=>void run(load);$('status-filter').onchange=()=>void run(load);$('logout').onclick=()=>{access='';location.reload();};
document.addEventListener('click',e=>{const id=e.target.dataset.block;if(id)void run(async()=>{await api('/v1/admin/customers/'+id+'/block',{},'POST');await load();message('Status do cliente atualizado.');});const edit=e.target.dataset.edit;if(edit)void run(async()=>{const rows=await api('/v1/admin/customers');showForm(rows.find(r=>r.id===edit));});});
